[package]
name = "zalgo"
version = "0.0.0"
authors = [ "Nathaniel Daniel <nathaniel.daniel12@gmail.com>" ]
edition = "2021"

[dependencies]
rand = { version = "0.8.5", default-features = false, features = [ "small_rng", "getrandom" ] }
